export const endpoints = Object.freeze({
  display: '/xsxk/zzxkyzb_cxZzxkYzbDisplay.html',
  chosenPanel: '/xsxk/zzxkyzb_cxZzxkYzbChoosed.html',
  chosenDisplay: '/xsxk/zzxkyzb_cxZzxkYzbChoosedDisplay.html',
  coursePage: '/xsxk/zzxkyzb_cxZzxkYzbPartDisplay.html',
  teachingClasses: '/xsxk/zzxkyzbjk_cxJxbWithKchZzxkYzb.html',
  titleCheck: '/xsxk/zzxkyzb_cxXkTitleMsg.html',
  conflictCheck: '/xsxk/zzxkyzb_cxCtKcZyZzxkYzb.html',
  textbookCheck: '/xsxk/zzxkyzb_cxCheckJckg.html',
  textbookView: '/xsxk/zzxkyzb_cxXsxzjcView.html',
  saveSelection: '/xsxk/zzxkyzbjk_xkBcZyZzxkYzb.html',
  quickSelect: '/xsxk/zzxkyzb_xkZzxkyzbQuickly.html',
  cancelTitleCheck: '/xsxk/zzxkyzb_cxTkTitleMsg.html',
  cancelInTimeCheck: '/xsxk/zzxkyzb_xkJcInXksjZzxkYzb.html',
  smsVerify: '/xkgl/common_cxCheckXsxkYzm.html',
  dropSelection: '/xsxk/zzxkyzb_tuikBcZzxkYzb.html',
  saveOrder: '/xsxk/zzxkyzb_xkBcZypxZzxkYzb.html',
  checkWeightEditable: '/xsxk/zzxkyzb_xkJcXgqzqxZzxkYzb.html',
  saveWeight: '/xsxk/zzxkyzb_xkBcQzZzxkYzb.html',
  textbookUpdate: '/xsxk/zzxkyzb_cxUpdateJcydbj.html',
  waitlistAdd: '/xsxk/zzxkyzb_xkBcZzxkyix.html',
  waitlistRemove: '/xsxk/zzxkyzb_tuikBcXkyix.html',
  listenerCheck: '/jxrwbmgl/jxrwxmbm_cxJxxmbmCheckCount.html',
  listenerAdd: '/jxrwbmgl/jxrwxmbm_zjJxrwxmbm.html',
  listenerRemove: '/jxrwbmgl/jxrwxmbm_scJxrwxmbm.html'
});
